services:
  - type: web
    name: univote-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node auth/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: 20.11.0
